name: Segundo Workflow - Verificar e Executar

on:
  repository_dispatch:
    types: [workflow_trigger]

jobs:
  receber-id:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Verificar ID recebido
        run: |
          echo "ID do primeiro workflow recebido: ${{ github.event.client_payload.workflow_id }}"
          echo "SHA recebido: ${{ github.event.client_payload.sha }}"
          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
      - name: Verificar status do Workflow
        id: verificar-status
        uses: actions/github-script@v6
        with:
          script: |
            const workflowId = "${{ github.event.client_payload.workflow_id }}";
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            try {
              const response = await github.rest.actions.getWorkflowRun({
                owner,
                repo,
                run_id: workflowId,
              });
              const status = response.data.status;
              const conclusion = response.data.conclusion;
              console.log(`Status do Workflow: ${status}`);
              console.log(`Conclusão do Workflow: ${conclusion}`);
              if (status !== "completed") {
                throw new Error(`O Workflow com ID ${workflowId} ainda está em execução.`);
              }
              if (conclusion !== "success") {
                throw new Error(`O Workflow com ID ${workflowId} não foi concluído com sucesso. Conclusão: ${conclusion}`);
              }
              console.log(`O Workflow com ID ${workflowId} foi concluído com sucesso.`);
              core.setOutput('conclusion', conclusion);  # Set the conclusion as an output
              return conclusion;
            } catch (error) {
              console.error(`Erro ao verificar o status do Workflow: ${error.message}`);
              throw error;
            }
      - name: Criar Status Check
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const sha = "${{ github.event.client_payload.sha }}"; 
            try {
              await github.rest.repos.createCommitStatus({
                owner,
                repo,
                sha,
                state: "success",  # Pode ser "success", "failure" ou "pending"
                context: "Processamento Externo Concluído",  # Nome do status check
                description: "A API externa concluiu o processamento.",
              });
              console.log("Status check criado com sucesso.");
            } catch (error) {
              console.error("Erro ao criar status check:", error);
              throw error;
            }
      - name: Usar Conclusão
        run: echo "Conclusão do Workflow: ${{ steps.verificar-status.outputs.conclusion }}"

