name: Primeiro Workflow - Acionar API 

on:
  workflow_dispatch:

jobs:
  acionar_api:
    runs-on: ubuntu-latest
    steps:
      - name: Acionar API
        run: |
          curl -X POST https://api.github.com/repos/felipejcsouza/teste-workflows/dispatches -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GHTK }} " \
            -d '{
            "event_type": "workflow_trigger",
            "client_payload": {
            "workflow_id": "'"${{ github.run_id }}"'"
            }
            }'
        env:
          API_KEYS: ${{ secrets.API_KEY }}
      - name: Salvar ID do workflow
        run: |
          echo "WORKFLOW_ID=${{ github.run_id }}"

      - name: Exibir ID do Workflow
        run: |
          echo "ID do workflow: ${{ env.WORKFLOW_ID }}"
          
