name: Segundo Workflow - Verificar e Executar

on:
  repository_dispatch:
    types: [workflow_trigger]

jobs:
  receber-id:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Verificar ID recebido
        run: |
          echo "ID do primeiro workflow recebido: ${{ github.event.client_payload.workflow_id }}"
          echo "SHA recebido: ${{ github.event.client_payload.sha }}"
          echo "PR Number: ${{ github.event.client_payload.pr_number }}"
      - name: Verificar status do Workflow
        id: verificar-status
        uses: actions/github-script@v6
        with:
          script: |
            const workflowId = "${{ github.event.client_payload.workflow_id }}";
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            try {
              const response = await github.rest.actions.getWorkflowRun({
                owner,
                repo,
                run_id: workflowId,
              });
              const status = response.data.status;
              const conclusion = response.data.conclusion;
              console.log(`Status do Workflow: ${status}`);
              console.log(`Conclusão do Workflow: ${conclusion}`);
              if (status !== "completed") {
                throw new Error(`O Workflow com ID ${workflowId} ainda está em execução.`);
              }
              if (conclusion !== "success") {
                throw new Error(`O Workflow com ID ${workflowId} não foi concluído com sucesso. Conclusão: ${conclusion}`);
              }
              console.log(`O Workflow com ID ${workflowId} foi concluído com sucesso.`);
              core.setOutput('conclusion', conclusion); 
              return conclusion;
            } catch (error) {
              console.error(`Erro ao verificar o status do Workflow: ${error.message}`);
              throw error;
            }
            
      - name: Send status to PR
        uses: jbuettnerbild/send-job-status-to-pr-action@v1
        with:
          state: "${{ job.status }}"
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          description: "The build result is: ${{ job.status }}"
          context: "receber-id"
          repository: "${{ github.repository }}"
          github_token: "${{ secrets.GHTK }}"
          sha: "${{ github.event.client_payload.sha }}"
      - name: Usar Conclusão
        run: |
          echo "Conclusão do Workflow: ${{ steps.verificar-status.outputs.conclusion }}"
  

